Server work
mjh9585/AdvancedVoiceChat pull request #4
Opened 2023-12-05 16:57 UTC by promiseo123

2023-12-05 21:50 UTC, mjh9585 requested changes
I was mistaken about the redirect routes, but overall good start. There are a couple pieces necessary functionality currently missing though. Please review the project document for the detailed requirements.

2023-12-05 21:50 UTC, mjh9585 commented on Webserver/site.py
> +        return redirect(url_for('/login'))
I was mistaken on these redirects. It is just 'login' and 'index' without the slash.

2023-12-05 21:50 UTC, mjh9585 commented on Webserver/site.py
> +def login():
This route needs to handle both GET and POST.
- GET: render template
- POST: handle login

Please review the project Document

2023-12-05 21:50 UTC, mjh9585 commented on Webserver/site.py
> +        ws.send(data)
The received message needs to be forwarded to the requested client.

2023-12-05 21:50 UTC, mjh9585 commented on Webserver/site.py
> +app.config['SECRET_KEY'] = 'secret_key'
This should probably be set somewhere else, but for this it is fine. Please assign it a random key value. https://randomkeygen.com/ is a good site for generating these

2023-12-07 03:39 UTC, promiseo123 commented on Webserver/site.py
> +        ws.send(data)
do you mean that a parameter for a user to forward data to needs to be used?

2023-12-16 06:38 UTC, merged